include:
  - path: ./docker/speech.docker-compose.yml
    env_file: ./.env
  - path: ./docker/postgres.docker-compose.yml
    env_file: ./.env
  - path: ./docker/temporal.docker-compose.yml
    env_file: ./.env
  - path: ./docker/minio.docker-compose.yml
    env_file: ./.env
