"""add transcript full text search

Revision ID: 3dfffcc613c0
Revises: 6117f58547c8
Create Date: 2026-10-04 03:29:10.154647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3dfffcc613c0'
down_revision: Union[str, Sequence[str], None] = '6117f58547c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('communication_representations', sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("CASE WHEN type = 'text' THEN to_tsvector('russian', coalesce(payload ->> 'content', '')) END", persisted=True), nullable=True))
    op.create_index('ix_communication_representations_search', 'communication_representations', ['search_vector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_communication_representations_search', table_name='communication_representations', postgresql_using='gin')
    op.drop_column('communication_representations', 'search_vector')
    # ### end Alembic commands ###
