"""create communications

Revision ID: 6117f58547c8
Revises: 
Create Date: 2026-10-02 00:27:30.219136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6117f58547c8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default EntityMixin (ddf); PostgreSQL 18+ генерирует UUIDv7 нативно
    op.execute("CREATE OR REPLACE FUNCTION uuid_generate_v7() RETURNS uuid LANGUAGE sql AS 'SELECT uuidv7()'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('communications',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('original_media_id', sa.UUID(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('external_source', sa.String(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('participants', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuid_generate_v7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_communications_external', 'communications', ['external_source', 'external_id'], unique=False)
    op.create_index(op.f('ix_communications_organization_id'), 'communications', ['organization_id'], unique=False)
    op.create_table('communication_representations',
    sa.Column('communication_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['communication_id'], ['communications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('communication_id', 'type')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('communication_representations')
    op.drop_index(op.f('ix_communications_organization_id'), table_name='communications')
    op.drop_index('ix_communications_external', table_name='communications')
    op.drop_table('communications')
    # ### end Alembic commands ###

    op.execute("DROP FUNCTION IF EXISTS uuid_generate_v7()")
